name: lango
description: "KI-gestÃ¼tzter Sprachlernbegleiter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  collection: ^1.19.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^9.0.5
  go_router: ^17.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/character/
